### ISSUE TITLE
activitymanager error (due to no data ?)

### ISSUE THREAD

**Issue by Athanasius** [aussig/BGS-Tally#100]
**Describe the bug**
```python
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\activitymanager.py", line 42, in save
    activity.save(path.join(self.bgstally.plugin_dir, FOLDER_ACTIVITYDATA, activity.tick_id + FILE_SUFFIX))
                                                                           ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**To Reproduce**
1. I've not actually been playing, so have *zero* data any time recently.
2. Run EDMC with BGS-Tally
3. See error on console.

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest build)
 - Plugin Version: 2.2.1 **git tag, not from .zip file**
 - EDMC Version: Current `develop` ( [c350782a67713565ae15a4201569932f158bea36 ](https://github.com/EDCD/EDMarketConnector/commit/c350782a67713565ae15a4201569932f158bea36) )

**Additional context**
I'd guess that `activity.tick_id` is None, so you need a check on that before invoking this code, possibly more of it above too.

**Comment by aussig** [comment]
Could I get a little more context:

1. Had you just upgraded to the 2.2.1 codebase, and if so do you recall what version you previously ran?
2. Does the 'Previous BGS Tallies' dropdown have anything in it?
3. What happens if you click the 'Latest BGS Tally' button - any exceptions thrown?

**Comment by Athanasius** [comment]
1. From the 2.2.0 tag
2. Yes, lots.  The most recent right now is from 2023-01-10, there are more than just this, but the image shows I have gaps. 
![image](https://user-images.githubusercontent.com/118007/212112113-cddc0f32-438c-4c80-9806-51e76b389da2.png)

3. No exceptions

Nor did I get the 'original' exception this time.  Possibly because that first run of 2.2.1 left some data behind that avoids it ?

**Comment by Athanasius** [comment]
No, no other BGS-Tally exceptions.  Although here's the *full* version of it:

```python
2023-01-12 14:39:19.994 UTC - ERROR - 21164:24668:24668 plug.notify_journal_entry:319: Plugin "BGS-Tally" failed
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\plug.py", line 316, in notify_journal_entry
    newerror = journal_entry(cmdr, is_beta, system, station, dict(entry), dict(state))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally\load.py", line 59, in journal_entry
    this.journal_entry(cmdr, is_beta, system, station, entry, state)
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\bgstally.py", line 167, in journal_entry
    if dirty: self.save_data()
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\bgstally.py", line 231, in save_data
    self.activity_manager.save()
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\activitymanager.py", line 42, in save
    activity.save(path.join(self.bgstally.plugin_dir, FOLDER_ACTIVITYDATA, activity.tick_id + FILE_SUFFIX))
                                                                           ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by aussig** [comment]
Thanks Ath, I'll try to work out how it got into a 'no tick ID' situation, and as a last resort also put some error-detection in place as you suggest.
