### ISSUE TITLE
Trade Profit (TrdProfit) is not being reported.

### ISSUE THREAD

**Issue by glaistyn** [aussig/BGS-Tally#121]
**Describe the bug**
TrdProfit is not being reported when trading at profit to stations/settlements.
Using default settings, several other users experiencing same behaviour.

**To Reproduce**
Trade commodities at profit to a station/settlement.

**Expected behavior**
TrdProfit to be reported.
Older versions appeared to do this with default settings.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Plugin Versio: 3.0.2
 - EDMC Version: 5.8.1

**Comment by aussig** [comment]
Could you send me some example player journals for play sessions where you are seeing this happening.

(Check the [reporting a bug section](https://github.com/aussig/BGS-Tally/wiki/Troubleshooting#reporting-a-bug) in the Troubleshooting guide for the journal location if you aren't sure where to find it.)

**Comment by aussig** [comment]
I've found a case where this can happen - if you disembark on foot, re-embark on your ship and then trade, BGS-Tally fails to log the purchase / sale / profit.
