### ISSUE TITLE
BGS-Tally underreports Exploration Data values -- or is it Elite's fault?

### ISSUE THREAD

**Issue by Jessidhia** [aussig/BGS-Tally#125]
**Describe the bug**
BGS-Tally seems to consistently underreport the value of sold exploration data to me, but when I tried to read the code to see why there would be an underreport, I found that BGS-Tally simply reads the TotalEarnings value from the log, which led to a realization that Elite itself underreports earnings in TotalEarnings.

I suspected this is could be potentially related to having a hired NPC crew member, but even if I add back the Amount in the NpcCrewPaidWage lines, they don't match the expected value from the game UI, or from the BaseValue (with or without Bonus).

**To Reproduce**
1. Make note of the value of the exploration data to be sold
2. Sell exploration data
3. Click on `Latest BGS Tally`
4. Check the corresponding faction's line item
5. See mismatch

**Expected behavior**
BGS-Tally should add the correct earning from exploration data sold.

However, I am not 100% certain that this is an ED client bug. I have no idea how to verify, but it's not impossible that what goes in TotalEarnings is what's *really* counted for BGS during the tick, and not the value in the UI.

**Screenshots**

BGS-Tally report line:
![image](https://github.com/aussig/BGS-Tally/assets/73085/1598e91b-b5db-4fbd-82d1-c39aed9d2cba)

{,Multi}SellExplorationData as they appear in EDDiscovery:
![image](https://github.com/aussig/BGS-Tally/assets/73085/1461b908-e8a7-42e6-9567-6d3867aefa14)

Note how BGS-Tally sees 15.3 million while EDDiscovery reports ~16.8 million (the non-Multi sales were done in a different system). EDDiscovery itself appears to have [a workaround for this issue](https://github.com/EDDiscovery/EliteDangerousCore/blob/eeff608de2689d628ec92bb6d5ce7e268bf19e40/EliteDangerous/JournalEvents/JournalExplorationData.cs#L110), which is why their reported Total does *not* match the log line, but it's only active in the MultiSellExplorationData lines, [not the single sales](https://github.com/EDDiscovery/EliteDangerousCore/blob/eeff608de2689d628ec92bb6d5ce7e268bf19e40/EliteDangerous/JournalEvents/JournalExplorationData.cs#L54).

Raw log entries for the screenshotted events (plus Npc line, minus system names for space)
```json
{"timestamp":"2023-07-18T10:47:32Z","event":"MultiSellExplorationData","Discovered":[],"BaseValue":16796132,"Bonus":65457,"TotalEarnings":15344070}
{"timestamp":"2023-07-18T10:47:32Z","event":"NpcCrewPaidWage","NpcCrewName":"Rosaline Mcpherson","NpcCrewId":147605184,"Amount":1256679}
{"timestamp":"2023-07-18T10:37:41Z","event":"SellExplorationData","Systems":[],"Discovered":[],"BaseValue":24270,"Bonus":0,"TotalEarnings":22086}
{"timestamp":"2023-07-18T10:37:41Z","event":"NpcCrewPaidWage","NpcCrewName":"Rosaline Mcpherson","NpcCrewId":147605184,"Amount":1808}
{"timestamp":"2023-07-18T10:37:27Z","event":"SellExplorationData","Systems":[],"Discovered":[],"BaseValue":19348,"Bonus":8087,"TotalEarnings":17607}
{"timestamp":"2023-07-18T10:37:27Z","event":"NpcCrewPaidWage","NpcCrewName":"Rosaline Mcpherson","NpcCrewId":147605184,"Amount":1442}
{"timestamp":"2023-07-18T10:37:19Z","event":"SellExplorationData","Systems":[],"Discovered":[],"BaseValue":30940,"Bonus":0,"TotalEarnings":28156}
{"timestamp":"2023-07-18T10:37:19Z","event":"NpcCrewPaidWage","NpcCrewName":"Rosaline Mcpherson","NpcCrewId":147605184,"Amount":2305}
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin Version v3.0.2
 - EDMC Version v5.8.1

**Comment by aussig** [comment]
Many thanks for the detailed report, and your research into the problem.  I wasn't aware that `TotalEarnings` can sometimes be incorrect, or missing altogether.

This could also explain an occasional issue where BGST doesn't report an exploration data sale at all.

 I'll take a look at adjusting `TotalEarnings` if it is less than `BaseValue` + `Bonus`
