### ISSUE TITLE
Plugin Fails to Load if EliteBGS is down

### ISSUE THREAD

**Issue by demon5760** [aussig/BGS-Tally#139]
**Describe the bug**
While doing some testing today I found that elitebgs.app was down, which causes the plugin to fail to load. 

**To Reproduce**
Kind of tricky since you need elitebgs.app to be down... but when it is (or if you can simulate it being down on our local)
Open EDMC and note that the plugin fails to load

**Expected behavior**
Ideally (not sure how realistic this is with EDMC) there would be some mechanism to have it retry, but there are lots of options. I don't think I'm in a solid position to make a recommendation, but I wanted to raise the situation for awareness.

I can even see a "This worked as expected" given it does present an error message. And maybe the error message could provide a little more info like "close out and try again in a little while

**Screenshots**
![image](https://github.com/aussig/BGS-Tally/assets/110693139/2d109675-c4b4-464b-9189-dcfebeec75c0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin Version 3.2.0-a1
 - EDMC Version 5.9.5+6f2ba8d

**Additional context**
Log Entry:
```
2023-09-12 11:47:15.341 UTC - ERROR - 21456:2260:2260 <plugins>.BGS-Tally.bgstally.tick.Tick.fetch_tick:36: Unable to fetch latest tick from elitebgs.app: HTTPSConnectionPool(host='elitebgs.app', port=443): Read timed out. (read timeout=10)
2023-09-12 11:47:15.342 UTC - ERROR - 21456:2260:2260 plug.Plugin.__init__:75: : Failed for Plugin "BGS-Tally"
Traceback (most recent call last):
  File "plug.pyc", line 66, in __init__
  File "C:\Users\me\AppData\Local\EDMarketConnector\plugins\BGS-Tally\load.py", line 28, in plugin_start3
    raise Exception("BGS-Tally couldn't continue because the current tick could not be fetched")
Exception: BGS-Tally couldn't continue because the current tick could not be fetched
2023-09-12 11:47:15.343 UTC - ERROR - 21456:2260:2260 plug.load_plugins:187: Failure loading found Plugin "BGS-Tally"
Traceback (most recent call last):
  File "plug.pyc", line 185, in load_plugins
  File "plug.pyc", line 66, in __init__
  File "C:\Users\me\AppData\Local\EDMarketConnector\plugins\BGS-Tally\load.py", line 28, in plugin_start3
    raise Exception("BGS-Tally couldn't continue because the current tick could not be fetched")
Exception: BGS-Tally couldn't continue because the current tick could not be fetched
```

**Comment by demon5760** [comment]
I think the underlying question here is should an inability to load ticket information prevent the entire plugin from loading, or just prevent features that rely on the tick?

**Comment by demon5760** [comment]
The one feature I know is popular in my squadron, is the Target Commander Information, which wouldn't rely on tick information (I don't think).

Its not like Elite BGS goes down a lot. I think this is only the second time I can remember, so its probably not worth the code complexity of having some features work and not.

Agreed with your reasoning on not using older tick data the confusion level on that could be high. I do appreciate your thoughts and insights. I suppose a counter argument for the error message is there is some pretty limited real estate there so anything more verbose probably becomes problematic. I'll defer to you on closing this or not at this point, but I think your explanations make sense, and current behavior/experience is good.

**Comment by aussig** [comment]
Yeah, it does go down occasionally but it's very bad luck if it's down just as you are starting up EDMC - If it goes down _while_ BGS-Tally is running, the plugin doesn't halt - it just keeps trying elitebgs occasionally, and any activity keeps being tallied to the current tick.
