### ISSUE TITLE
Progress panel often not properly loading

### ISSUE THREAD

**Issue by maehara-uk** [aussig/BGS-Tally#153]
Progress panel often doesn't full load, just shows as per attached screenshot.  This is not consistent - sometimes will properly load, sometimes not, and on occasions it loads it seems that activity is still being correctly recorded - but makes the plugin unreliable to use if I can see / copy activity report for pasting into our Discord.

<img width="1320" alt="Screenshot 2024-01-01 at 15 29 45" src="https://github.com/aussig/BGS-Tally/assets/49649425/e7fb1049-c61a-491e-b0fd-7444bd93cd89">

Have run through the Troubleshooting page of the Wiki, but nothing there that resolves issue.
Have tried restarting each / all of EDMC, BGS Tally plugin, Elite (reload from desktop), and reboot PC; none seem to resolve issue; as noted it's intermittient.
Have aldo tried jumping to new system / docking at new starport, also no joy.

**To Reproduce**
1. Load EDMC / ensure BGS Tally plugin is active
2. Click on 'Latest BGS Tally' button
3. Observe progress window as per screenshot

**Expected behavior**
Should load full progress window as per screenshots in Wiki / instructions

**Desktop (please complete the following information):**
 - OS: Windows 10, 22H2
 - Plugin Version 3.3.0]
 - EDMC Version 5.10.0 +b0b9913 (update check reports this is current version)

**Comment by aussig** [comment]
Interesting, can you send me your EDMC debug log file just after the window shows up empty. If you're on Discord then best DM it to me via my server: https://discord.gg/YDNVtjPnnm

**Comment by aussig** [comment]
Nothing further heard, so closing this one.
