### ISSUE TITLE
Search and Rescue should only apply in TW systems

### ISSUE THREAD

**Issue by aussig** [aussig/BGS-Tally#186]
TW S&R hand-ins should only be tallied for systems in TW.

**Comment by dwomble** [comment]
I'm not entirely sure what you mean, but handing in escape pods has a BGS impact regardless of the TW.

**Comment by aussig** [comment]
Sorry this was a quick note I made when I had no time to write up fully - currently even if an escape pod is scooped in a system not in TW state, it still creates a TW report for that system. 

Thats wrong - systems not in TW should never show up in the TW report. 

The question of escape pods affecting the BGS is interesting though, honestly I had never heard this. Can you link any evidence of this being tested?  If so, does it affect the scoop system or the hand-in system BGS, and which faction in each case?

**Comment by DerekAudience** [comment]
I don't have empirical evidence to hand but it's the concensus from the BGS managers of CLBF (the largest PMF in the game) who've been at this for years and years. The other thing is the negative impact of black market trading. I'm working on getting some actual data on that.

**Comment by dwomble** [comment]
I don't have solid empirical evidence it's the word from the BGS experts in CLB (the largest PMF in the game) who've been at it a long time. I'm told it's a positive influence for the faction that owns the station at which you hand in the pods. They also tell me that black market trading has a significant deleterious impact which is something I'm testing right now.

**Comment by aussig** [comment]
Interesting on escape pods and BGS, I'm going to follow up with our BGS experts too, see whether this is a well known factor.

And yes, BM trading is a known factor in the BGS, and BGS-Tally tracks and reports it.

**Comment by aussig** [comment]
Ok, the consensus here is that it's a very minor effect, but if there's any effect then BGS-Tally ought to track it, so I've raised a new issue for that: #194
