### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by aussig** [aussig/BGS-Tally#189]
We've finally come to the stage, with enough CMDRs using the plugin, to put the effort in to translations. For initial launch, we'll need a few languages so if you would like to volunteer to translate these or any other languages, ping a reply here or mention it in the Discord

- [x] Italian - @GLWine 
- [ ] #205
- [ ] #206
- [x] German - CMDR Ryan Murdoc
- [x] Turkish - CMDR Yu-gen

Also:
- [x] Add thankyou to translators

**Comment by aussig** [comment]
EDMC project states `.strings` files as the [official documented way](https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md#localisation)

Look at [crowdin.com](https://crowdin.com/) and [poedit.net](https://poedit.net/) (or possibly others) as platforms for managing localisation.

**Comment by dwomble** [comment]
At the same time could we consider making it possible to have different discord post formats?

I was going to ask if you'd be interested in a PR that enabled different versions of the output messages but it ties in fairly nicely with this. Moving to gettext or some other i18n system requires replacing all the output text strings with calls to a function which is what is needed for what I'm looking to achieve.

**Comment by aussig** [comment]
> At the same time could we consider making it possible to have different discord post formats?
> 
> I was going to ask if you'd be interested in a PR that enabled different versions of the output messages but it ties in fairly nicely with this. Moving to gettext or some other i18n system requires replacing all the output text strings with calls to a function which is what is needed for what I'm looking to achieve.

I've created a new issue for this: #195

**Comment by aussig** [comment]
Overall mechanism and first languages are complete, so closing this. Opened separate issues for French and Spanish.
