### ISSUE TITLE
In TW warfare VIP are not counted

### ISSUE THREAD

**Issue by j-cybertroll** [aussig/BGS-Tally#193]
When delivering passenger missions, the VIP ones don't count neither as missions nor as passengers evacuated.

**Comment by aussig** [comment]
> When delivering passenger missions, the VIP ones don't count neither as missions nor as passengers evacuated.

Could you send me a game journal with some examples of TW VIP and passenger evacuation missions, preferably with both pick-up and hand-ins.

**Comment by j-cybertroll** [comment]
Picking up line #1721
Delivered line #2062
[Journal.2024-03-26T105453.01.log](https://github.com/aussig/BGS-Tally/files/14758990/Journal.2024-03-26T105453.01.log)

**Comment by aussig** [comment]
Nice, thank you. That's fixed for next release.
