### ISSUE TITLE
TW - BGS Tally does not register VIP rescue missions

### ISSUE THREAD

**Issue by j-cybertroll** [aussig/BGS-Tally#229]
I took 20 missions. 8 for wounded and 12 for passengers. 3 of them were VIP. 
VIP did not register in the tally:

Missions are in the screenshot. 
VIP missions in logs are registered as "Name":"Mission_TW_RefugeeVIP_name"
![image](https://github.com/aussig/BGS-Tally/assets/165035906/79405065-ffd7-4c9c-a683-ea90a488c3dc)
![image](https://github.com/aussig/BGS-Tally/assets/165035906/ca0e9a79-d6a0-4b23-b76d-b1f49d99c30c)

**Comment by aussig** [comment]
That issue is fixed in v4.0.0, which hasn't been released yet.
