### ISSUE TITLE
The Fleet Carrier screen is void

### ISSUE THREAD

**Issue by GLWine** [aussig/BGS-Tally#241]
**Describe the bug**
By opening the section dedicated to Carrier, the screen appears very small and empty.
It is not possible to trace any component present in that screen.
In the EDMC settings, the CAPI section connected to Fleet Carriers is active.

**Log files**
[EDMarketConnector-debug-P1.log](https://github.com/aussig/BGS-Tally/files/15358989/EDMarketConnector-debug-P1.log)
[EDMarketConnector-debug-P2.log](https://github.com/aussig/BGS-Tally/files/15358990/EDMarketConnector-debug-P2.log)
[EDMarketConnector.log](https://github.com/aussig/BGS-Tally/files/15358991/EDMarketConnector.log)

**To Reproduce**
1. On the home page, click on the Fleet Carrier icon
2. The window appears incomplete and empty

**Expected behavior**
After opening the Fleet Carrier section I would expect to see related information.

**Screenshots**
![BGS-Tally-interface](https://github.com/aussig/BGS-Tally/assets/54741923/fe5cc3c3-c41b-452f-ae2c-3149fc468a37)
![BGS-Tally-interface-and-setting](https://github.com/aussig/BGS-Tally/assets/54741923/b1abb265-81da-4e25-a743-41594c9b9e7a)

**Desktop:**
 - OS: Windows 11 and 10
 - Plugin Version 3.6.1 to 4.0.0-a2
 - EDMC Version 5.10.6

**Comment by aussig** [comment]
That is definitely breaking when trying to initially load the window so there should be errors logged to the EDMC log files. 

Could you attach your logs to this issue or DM them to me on Discord if you want to keep them private. See [the troubleshooting page](https://github.com/aussig/BGS-Tally/wiki/Troubleshooting#reporting-a-bug) for the location of these.

**Comment by GLWine** [comment]
> That is definitely breaking when trying to initially load the window so there should be errors logged to the EDMC log files. 
> 
> Could you attach your logs to this issue or DM them to me on Discord if you want to keep them private. See [the troubleshooting page](https://github.com/aussig/BGS-Tally/wiki/Troubleshooting#reporting-a-bug) for the location of these. 

The log files are already present in the original post.
However, if you need specific logs in which I have to perform specific actions, please tell me the sequence to perform.

**Comment by GLWine** [comment]
> That is definitely breaking when trying to initially load the window so there should be errors logged to the EDMC log files. 
> 
> Could you attach your logs to this issue or DM them to me on Discord if you want to keep them private. See [the troubleshooting page](https://github.com/aussig/BGS-Tally/wiki/Troubleshooting#reporting-a-bug) for the location of these. 

The log files are already present in the original post.
However, if you need specific logs in which I have to perform specific actions, please tell me the sequence to perform.
