### ISSUE TITLE
Wrong translation / typo: german "previous BGS tally"

### ISSUE THREAD

**Issue by netchild** [aussig/BGS-Tally#256]
**Describe the bug**
Typo HGS -> BGS

**How to fix**
"Vorherige HGS-Tallies" should be "Vorherige BGS-Tallies".

Note, "Tally" or "Tallies" is not German. "Tally" could be "Liste", and "Tallies" be translated as "Listen".

**Comment by aussig** [comment]
This is fixed in the translation strings for the next release.
