### ISSUE TITLE
Discord Report Preview is blank, nothing gets posted through webhooks.

### ISSUE THREAD

**Issue by leobrog** [aussig/BGS-Tally#272]
**Describe the bug**
Discord Report Preview is blank, nothing gets posted through webhooks.

**To Reproduce**
1. Go to 'EDMC main screen'
2. Click on 'Latest BGS Tally'
3. Nothing is printed in the "Discord Report Preview"

**Expected behavior**
Discord Report Preview shows the formatted text and the "Post to Discord" button actually posts. Activity is still being recorded.

**Screenshots**
![image](https://github.com/user-attachments/assets/b6565254-36e8-4812-b1b7-ca823360ef23)

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin Version: v4.1.0
 - EDMC Version: 5.12.0+cc6e200

**Log Files**
Please attach the following three log files:

[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17157664/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/user-attachments/files/17157665/EDMarketConnector.log)

**Comment by aussig** [comment]
Many thanks for the bug report. This was due to a change in EDMC 5.12.0 which I have now added a workaround for. I'll release a bugfix version today.
