### ISSUE TITLE
Post Activity to Web Service

### ISSUE THREAD

**Issue by aussig** [aussig/BGS-Tally#31]
For automatic collation of group BGS activities, it would be very useful to be able to post JSON data to an endpoint.

The webapp would need to secure access to the API using either a secret or by publishing unique API URLs per user (effectively the same, but embedding the secret in the URL).  Plugin would need to support the following functions:

* Create a BGS record for the current user and tick
* Update an existing record for the current user and tick
* Delete an existing record for the current user and tick? (probably not needed)

When elitebgs.app detects a tick, it assigns this a unique ID so we should use that ID to uniquely identify the tick records.

**Comment by cluster-fox** [comment]
Hi Aussig !
The BGS Record is a complicated way to do something the API endpoint should be dealing with.
Sending the BGS event as it happens is a lot more efficient in terms of using the API. Collection and processing can then be made on the API-endpoint.

We should maybe start a new thread to discuss API message format?

**Comment by aussig** [comment]
It was good to talk on Discord @cluster-fox. I think we should keep discussions over there, and I'll document any final decisions on API endpoints and specs here. We're getting closer to that discussion, as we are implementing our own server-side aggregation service, but there are a few other things the developer working on that side needs to get sorted first.

For the benefit of others, cluster-fox worked on a fork of tez's original BGS-Tally 2.0 project to incorporate an API integration to his Comguard app. The specific integration is in [send_data() here](https://github.com/tezw21/BGS-Tally-Comguard/blob/b63047df3808f497f76716abbc464234fbb21766/load.py#L571).

We are not tied to that format though as cluster-fox was planning on re-working their API anyway, so we'll map out a new API spec and all implement against that.
