### ISSUE TITLE
Tick not getting detected

### ISSUE THREAD

**Issue by Nicon4454** [aussig/BGS-Tally#38]
**Describe the bug**
To day is Wednesday 06/15/2022  12:38 UTC

BGS Tally has not detected the Tick for 2 days. Bgs Tally States the last tick was Monday June 13th at 03:21:08 UTC
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Plugin Version [e.g. 1.2.0]  1.9.0
 - EDMC Version [e.g. 5.1.3] 5.4.0+20c60a3

**Additional context**

**Comment by Nicon4454** [comment]
ok the tick has finally been detected on Friday June 17th  at 03:06:44

**Comment by aussig** [comment]
This wasn't a problem with BGS-Tally itself - it gets the tick from [elitebgs](https://elitebgs.app/tick) (https://github.com/Elite-Kode/elitebgs) and their tick detector (https://github.com/phelbore/TickDetector) was down for several days this week.

**Comment by aussig** [comment]
Thank you for the kind words, they are really appreciated!
