### ISSUE TITLE
Time Stamps

### ISSUE THREAD

**Issue by Tobytoolbag** [aussig/BGS-Tally#41]
It would be very useful to add a time and date stamp to the Discord code for each update posted so that BGS coordinators can see whether the values posted fall in the most recent Tick or previous ones.
If you're using the webhook method to post in a Discord channel, it only shows when the first update was posted, but does not show when any subsequent updates were posted. Obviously if you manually update using the copy/paste method, Discord shows when each update was posted.
Loving the plugin - it's proved so popular that most of our squadron BGS team is now using it!

**Comment by aussig** [comment]
That's a good idea, I'll add it to an upcoming version.

And thank you very much for the compliment, it's great to hear it's well liked and used!
