### ISSUE TITLE
[Suggestion] - Shorten the date/time format for 'last tick'

### ISSUE THREAD

**Issue by Athanasius** [aussig/BGS-Tally#45]
I *think* it's the length of the `Last BGS Tick` value that causes the EDMC window to get **so wide**.  I currently have `07:01:03 UTC Monday 08 August`.

I'd at least change this to use the short forms of "Day of week" and "Month name", i.e. `07:01:03 UTC Mon 08 Aug`.

But ideally I'd love an option to just use ISO8601 format, i.e. `2022-08-08 07:01:03Z`, or just drop the timezone information entirely, given it should be obvious that in-game/UTC is being quoted.

So, with the current `develop` branch at [b4194ae](https://github.com/aussig/BGS-Tally/commit/b4194ae5c8d25891d4028c29711db32b06e0f24c), line 1059 becomes:

`return datetime_object.strftime("%H:%M:%S UTC %a %d %b")`

or:

`return datetime_object.strftime("%Y-%m-%d %H:%M:%S")`

And now I look a bit closer, another way to save some width would be splitting the `BGS Tally (modified by Aussi) v1.9.0` string into the two columns the plugin uses otherwise.  I think just putting the version string over in the second column would likely be enough, as `BGS Tally Plugin Status` is almost as long as `BGS Tally (modified by Aussi)`, although you could also change the latter to `BGS Tally (Aussi)`.

**Comment by Athanasius** [comment]
You've managed to lose these changes when merging https://github.com/aussig/BGS-Tally/commit/cdb98b86d4d2eea0600f2f7b9f1439900aec7617 - in part due to that merge changing a lot of how things work.

**Comment by Athanasius** [comment]
New PR in #49  - simply re-adjust the UI display time format.

**Comment by aussig** [comment]
> New PR in #49  - simply re-adjust the UI display time format.

Apols, your change conflicted with a date format change I had done, and I didn't incorporate both changes.
