### ISSUE TITLE
Not reading Journal?

### ISSUE THREAD

**Issue by eralm237** [aussig/BGS-Tally#52]
**Describe the bug**
No matter what I do in game, Latest BGS Tally and Previous BGS Tally are blank. EDMC is running latest version

**To Reproduce**
1. Open EDMC
2. Play Elite: Dangerous
3. Do a mission or two, turn in combat bonds or bounties
4. Click "Latest BGS Tally" or "Previous BGS Tally"
5. See that both screens are blank or filled with zeros
6. Open bgs-tally plugins folder, open Yesterday Data.txt see a bunch of data and all zero's
7. Open Today Data. txt and see a bunch of data and all zero's for data
8. Click on File Properties and files in 6&7 are NOT read-only
9. Re-launch EDMC
10. go do another mission
11. 6&7 are still filled with zero's

Tried a Fresh install
1. Opened Plugins folder, deleted BGS-Tally
2. Closed EDMC
3. Pasted BGS-Tally v 1.10 folder into Plugins
4. Opened EDMC
5. Noticed Webhook was never cleared
6. Open bgs-tally plugins folder, open Yesterday Data.txt see a bunch of data and all zero's
7. Open Today Data. txt and see a bunch of data and all zero's for data

**Expected behavior**
No zero's on files, and inf and missions displayed ready for posting in discord

**Screenshots**
![image](https://user-images.githubusercontent.com/112424441/187274190-195cc197-2a53-4e75-af56-b1a5f8c3e2af.png)
![image](https://user-images.githubusercontent.com/112424441/187274236-da737d0a-51a6-4802-b159-d59c217a8e16.png)
![image](https://user-images.githubusercontent.com/112424441/187274282-e77132a6-ac06-4ecb-8d56-f0ab7760ce02.png)
![image](https://user-images.githubusercontent.com/112424441/187274386-c436949d-0fd8-4d56-95e6-8094972bc233.png)
![image](https://user-images.githubusercontent.com/112424441/187274434-066c61e0-1c2b-4795-ab9d-a38f20300c02.png)
![image](https://user-images.githubusercontent.com/112424441/187274539-c3b62f49-e434-46fe-968a-fa70b164e646.png)
![image](https://user-images.githubusercontent.com/112424441/187274634-d649c763-6cff-43d3-b1af-9ae65cb07ad9.png)
![image](https://user-images.githubusercontent.com/112424441/187274948-a7e457df-4332-4e8a-ae22-e0a42b75d81f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin Version BGS-Tally 1.10
 - EDMC Version 5.4.1+1354c3

** Extra notes: 
EDMC is reading journal and displaying information correctly on main screen. (last image)

**Comment by aussig** [comment]
Hmm, odd. This is the first report I've had of this, and you've tried everything I might have suggested. Next step is you'll need to send me yourEDMC logs:

1. `%LOCALAPPDATA%\Temp\EDMarketConnector.log`
2. `%LOCALAPPDATA%\Temp\EDMarketConnector\EDMarketConnector-debug.log`

**Comment by eralm237** [comment]
Files you requested are attached. Also something odd: did absolutely nothing with it, went and watched a stream on Twitch (and cook supper). It then had data for the current day’s tick. Not previous day’s.  If I have done anything in the logs that I have not mentioned, I do apologize, tried to write up what I did correctly from memory. So, I went ahead and added two other plug-ins to see if they worked. So far the Canonn plug in works and Spansh does too. (Didn’t want to add too many plug ins in case had to re-install EDMC). Megan From: aussigSent: Tuesday, August 30, 2022 12:35 PMTo: aussig/BGS-TallyCc: eralm237; AuthorSubject: Re: [aussig/BGS-Tally] Not reading Journal? (Issue #52) Hmm, odd. This is the first report I've had of this, and you've tried everything I might have suggested. Next step is you'll need to send me yourEDMC logs:%LOCALAPPDATA%\Temp\EDMarketConnector.log%LOCALAPPDATA%\Temp\EDMarketConnector\EDMarketConnector-debug.log—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by aussig** [comment]
I didn't get the log attachments because you replied by email. Could you attach directly in GitHub.

**Comment by eralm237** [comment]
Sorry, new to EDMC and github. Did these attach? 

[EDMarketConnector.log](https://github.com/aussig/BGS-Tally/files/9481639/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/aussig/BGS-Tally/files/9481640/EDMarketConnector-debug.log)

**Comment by aussig** [comment]
I don't see any problems reported at all with BGS-Tally - it's loading correctly, terminating correctly and not logging any errors. Has it started consistently working for you now?  All I can think is there was an issue with the game writing to your disk, or EDMC picking up log entries. Did you have disk capacity issues, for example?

**Comment by eralm237** [comment]
Sorry for the delay, IRL is crazy. It's ok on working now, but it seems to have to be running about 10 minutes PRIOR to me starting my game, OR wait 15min in game for it to start registering things. I don't know why. It wouldn't surprise me if this is just a strange bug that has no clean resolution. (This happens often in my life with computers). Sometimes though it'll note a system INF increase in a place I've not been to, or did anything in besides fuel scoop the star. I don't know, don't worry about it.

**Comment by aussig** [comment]
If you have problems like this generally with your computer, it might be an issue with the system and it's probably worth spending some time running system checks (to ensure your Windows install is not corrupted) including a disk check (to ensure you don't have drive problems).

The behaviours you've mentioned are very unique, so I'll close this one as cannot replicate.
