### ISSUE TITLE
Enhanced INF reporting

### ISSUE THREAD

**Issue by pan-mroku** [aussig/BGS-Tally#70]
Since [2 INF++ !=  INF++++](https://forums.frontier.co.uk/threads/how-does-the-levels-of-rewards-scale.557024/post-8760253), would it be possible to choose if plugin writes out all INF rewards separately or (as it is now) sums all up?

**Comment by aussig** [comment]
Although that’s correct, I (and I’m sure I can speak for Tez too) wanted to keep reports easy, clear and straightforward to interpret.  I think listing every individual INF contribution would be unwieldy, and in a large Squadron would get difficult to understand.

**Comment by pan-mroku** [comment]
So maybe it could be a check in settings that by default would be to sum the contribution?

**Comment by aussig** [comment]
I’ll have a think about it, particularly how to present the results in a neat and clean way. 

It doesn’t matter whether it’s an optional feature, I would only implement something if it works well and is useable.

**Comment by aussig** [comment]
A possible layout:

```
.INF: 41 (+++++ x 4, ++++ x 2, +++ x 1, + x 10)
```

**Comment by pan-mroku** [comment]
Personally I would opt for the first option so it's clear which number is what but if you prefer the second one, that's still perfect to have for me

**Comment by aussig** [comment]
Yeah the first is clearer but takes more space, the second is neater but less obvious, especially if e.g. you've only done one mission:

```
.INF: 5 (5️⃣ x 1)
```

Not obvious what that means, until the user gets used to the format.

**Comment by aussig** [comment]
Might be ok using the compact format once #90 is implemented.

**Comment by aussig** [comment]
Another user has requested that primary and secondary INF are split in the reports, e.g.:
```
[HIP 20485 Corp.] - .INF 🅟+12 🅢+4; 
```

Seems like a nice addition, to make it clearer whether the INF was due to a secondary unanticipated effect.  

How to combine these two requests?

Perhaps we have a new 'detailed INF' setting that could combine with the 'secondary INF' setting to produce something like this:

Secondary INF: on; Detailed INF: on
```
[HIP 20485 Corp.] - .INF 🅟+41 (5️⃣ x 4, 4️⃣ x 2, 3️⃣ x 1, 1️⃣ x 10) 🅢+4; 
```
Secondary INF: off; Detailed INF: on
```
[HIP 20485 Corp.] - .INF +41 ((5️⃣ x 4, 4️⃣ x 2, 3️⃣ x 1, 1️⃣ x 10);
```
Secondary INF: on; Detailed INF: off
```
[HIP 20485 Corp.] - .INF 🅟+41 🅢+4; 
```
Secondary INF: off; Detailed INF: off
```
[HIP 20485 Corp.] - .INF +41;
```

**Comment by pan-mroku** [comment]
That way we don't see which systems and factions are affected by the secondary INF. And there is a corner case when we might be interested in that. Personally I like how it looks now, with printing system and faction. But it is a corner case

**Comment by aussig** [comment]
I’m not suggesting the overall structure of system and faction is changed, just how INF is displayed within each faction. 

In most cases there *won’t* be both pro and sec INF for the same faction in the same system, but the 🅟 / 🅢 label would still show which type the INF is.

**Comment by pan-mroku** [comment]
Ah. All good to me then :)

But we're loosing the separate values on secondary. Maybe something like this?
`[faction]  - .INF 🅟+41 (5️⃣ x 4, 4️⃣ x 2) 🅢+5 (5️⃣ x 1)`
The rest the same

**Comment by aussig** [comment]
Yes, that would be ok, as it would be tracking the mission INF rewards for both Pri and Sec INF.

Just thought of a slight snag though - the user can add manual INF via the BGS-Tally UI.  May need to track manual INF as a separate category.

**Comment by pan-mroku** [comment]
What's the use case? Shadow work? Reinstall?

Some things need manual insert anyway, like CZs. And it's prone to inaccuracies. Two CMDRs can input the CZ they did together; one might not remember exactly the numbers of INF rewards; etc.
So if it was up to me, I'd put manually inserted actions in separate group, below the usual counts. Or "better done than perfect" and wait if there's a request for this

**Comment by pan-mroku** [comment]
It's great! Thank you :)
