### ISSUE TITLE
Election INF disappeared 

### ISSUE THREAD

**Issue by Kumdanadam** [aussig/BGS-Tally#75]
After the latest Edmc version Election INF not showing up on latest BGS tally. checked logs plugin logs unable to see progress there also.

Before EDMC update ;

Activity after tick: 2022-12-18 13:20:50 (in-game time)
Hunza
[Talon Order] - .ElectionINF +14; .Expl 82.7K;  <<<<<---- expected to see.
Brokpa
[Brokpa Jet Life PLC] - .INF +2; 
HIP 23824
[HIP 23824 Jet Universal Company] - .INF +2; 
[HIP 23824 Independents] - .INF +2; 
HIP 42539
[Workers Party of HIP 42539] - .INF +2; 
Eban
[Official Eban Law Party] - .INF +2; 
Ganebucae
[Talon Order] - .INF +17; .Expl 155K; 
HIP 37735
[HIP 37735 Crimson Mob] - .INF -2; 

Posted at 2022-12-18 22:39:13 (in-game time)                                                   BGS-Tally v2.1.0

**Desktop (please complete the following information):**
 - OS: Windows 11. latest update.
 - Plugin Version [e.g. 2.1.0]
 - EDMC Version [e.g. 5.7.0]

**Comment by aussig** [comment]
To be clear, is it the Election INF or the Exploration data that's missing, or both?

**Comment by Kumdanadam** [comment]
Election INF only atm. no issue with exploration data.

**Comment by aussig** [comment]
I'll need to get a copy of your player journal file to take a look at why the INF has gone missions. Join my server: https://discord.gg/XU6TgyED
